### PR TITLE
Fix broken URL in README

### PR DESCRIPTION
**Pull request by TennyZhuang**

### CODE REVIEW

**Comment by tisonkun** [comment]
@TennyZhuang please sign CLA and we can proceed.

**Comment by TennyZhuang** [comment]
> @TennyZhuang please sign CLA and we can proceed.

Done

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
@rebelice do you have an idea why "Build & Test" doesn't run?

**Comment by tisonkun** [comment]
It seems the workflow configures wrongly. Let me try to fix it.

**Comment by tisonkun** [comment]
It is too complex to a course IMO. The Makefile is quite outdated and also the code. I don't want to fix them anyway.

cc @zhangyangyu @rebelice you may take a look at this issue. The build system of tinysql is quite mess.

**Comment by rebelice** [comment]
It's too hard to fix `Build & Test`. As far as I know, CI will keep failing until the entire tinysql is completed.

**Comment by tisonkun** [comment]
@rebelice I agree. Any progress on #83 ?

**Comment by rebelice** [comment]
@tisonkun Yes, I'm working on pushing the first PR. You may see it later.

**Comment by tisonkun** [comment]
@TennyZhuang thanks for your contribution. Although I think the contribution guide should be updated later.

**Comment by tisonkun** [comment]
Contribution guides of tinysql & tidb are different also.

**Pull request merged**
